### ISSUE TITLE
Updated libvpx to 1.4.0

### ISSUE THREAD

**Issue by superdump** [EricssonResearch/cerbero#14]
https://chromium.googlesource.com/webm/libvpx/+/v1.4.0

Looks like it has some more optimisations and stuff. :smile:

**Comment by nirbheek** [comment]
This commit from upstream fixes this: http://cgit.freedesktop.org/gstreamer/sdk/cerbero/commit/?id=fe687488ae93b86352780bcc2b00cb1d756edf37

**Comment by superdump** [comment]
Already merged. Closing.
