### ISSUE TITLE
Build Fail on Mac OSX 10.10

### ISSUE THREAD

**Issue by AlJohri** [EricssonResearch/cerbero#16]
[(31/32) openwebrtc-gst-plugins-static -> compile ]
[(31/32) openwebrtc-gst-plugins-static -> install ]
[(31/32) openwebrtc-gst-plugins-static -> post_install ]
[(31/32) openwebrtc-gst-plugins-static -> merge ]
[(32/32) openwebrtc -> fetch ]
[(32/32) openwebrtc -> extract ]
[(32/32) openwebrtc -> configure ]
Recipe 'openwebrtc' failed at the build step 'configure'
Traceback (most recent call last):
  File "./cerbero/build/oven.py", line 143, in _cook_recipe
    stepfunc()
  File "./cerbero/build/recipe.py", line 266, in <lambda>
    setattr(cls, step, lambda self, name=step: step_func(self, name))
  File "./cerbero/build/recipe.py", line 411, in _do_step
    stepfunc()
  File "/Users/atul/cerbero/recipes/openwebrtc.recipe", line 201, in configure
    raise Exception(err_rebuild)
Exception: No version_id found for the host darwin; try rebuilding it?
Select an action to proceed:
[0] Enter the shell
[1] Rebuild the recipe from scratch
[2] Rebuild starting from the failed step
[3] Skip recipe
[4] Abort

**Comment by superdump** [comment]
Hmm, sounds like a possible side effect of the recent OS X and Xcode updates. Can you try running bootstrap again for the targets of interest and the. Rerun the package command?

**Comment by AlJohri** [comment]
Sorry for the lack of details, at a hackathon at the moment. But I ran the bootstrap for OSX and the build was successful - then I ran the bootstrap for android and tried the build twice and both times got the same error above.

**Comment by superdump** [comment]
Cool! Which hackathon? What are you intending to do? :)

```
./cerbero-uninstalled -c config/cross-android-armv7.cbc cleanone openwebrtc
```

And then try again.

**Comment by superdump** [comment]
Wait, have you built OpenWebRTC for your host platform? That is necessary. Please run `package openwebrtc` for the host and then run it again for Android.

**Comment by superdump** [comment]
This should be working now. Please comment if it is still an issue.
