### ISSUE TITLE
Deps  are not being pinned for releases

### ISSUE THREAD

**Issue by AndrewJDR** [EricssonResearch/cerbero#35]
Currently, deps are not being pinned to particular commits, even upon release tags of cerbero.

For example:
https://github.com/EricssonResearch/cerbero/blob/v0.3.0/recipes/orc.recipe
https://github.com/EricssonResearch/cerbero/blob/v0.3.0/recipes/gst-plugins-ugly-1.0.recipe
And others. If you "grep commit.*master" in the recipies directory you can get a full list.

This means that if two people clone cerbero at v0.3.0, they may get completely different versions of several dependencies, depending upon when they did the checkout and how much activity recently occurred in those dependencies. This can get weird for reproducing bugs and things, because there's no way to say "Try it with this exact version of openwebrtc and its dependencies" without also communicating the commit SHAs of all the dependencies that aren't being pinned.

**Comment by AndrewJDR** [comment]
When I look at which dependencies actually get built (owr_bridge disabled in my case), only orc seems to be used. So maybe these deps aren't being pinned because they're not actually being used? Clarification appreciated! Thanks.

**Comment by sdroege** [comment]
gst-plugins-ugly is pinned to a specific commit too now

**Comment by AndrewJDR** [comment]
Thanks, I was about to do a PR but don't need to now :)
