### ISSUE TITLE
handle download errors

### ISSUE THREAD

**Issue by ck3mp3r** [EricssonResearch/cerbero#36]
Cerbero doesn't seem to handle download errors efficiently:

[(3/24) xz -> fetch ]
-----> Fetching tarball http://tukaani.org/xz/xz-5.2.0.tar.bz2 to /Users/christian/cerbero/sources/local/xz-5.2.0/xz-5.2.0.tar.bz2
[(3/24) xz -> extract ]
-----> Extracting tarball to /Users/christian/cerbero/sources/build-tools/xz-5.2.0
Unpacking /Users/christian/cerbero/sources/local/xz-5.2.0/xz-5.2.0.tar.bz2 in /Users/christian/cerbero/sources/build-tools
****\* Error running 'bootstrap' command:
Recipe 'xz' failed at the build step 'extract'...

If you try to access the file using a browser you get 403 forbidden, hence why the unzip fails if its trying to unzip source code of a resulting 403 page. I know you cannot do anything about where files are being hosted and how, but surely something can be done in handling the http error codes whilst downloading the files in question.

**Comment by ck3mp3r** [comment]
FYI: xz-5.2.1 is available and also downloadable.

**Comment by stefanalund** [comment]
Fixed in https://github.com/EricssonResearch/cerbero/pull/37.
