### ISSUE TITLE
Recipes for openssl pointing to missing version

### ISSUE THREAD

**Issue by ck3mp3r** [EricssonResearch/cerbero#49]
1.0.2f doesn't exist anymore, had to replace it with 1.0.2g in the recipes to work.

diff --git a/recipes/openssl.recipe b/recipes/openssl.recipe
index d0fc96a..9f59d9d 100644
--- a/recipes/openssl.recipe
+++ b/recipes/openssl.recipe
@@ -6,7 +6,7 @@ from cerbero.utils import shell, messages

 class Recipe(recipe.Recipe):
     name = 'openssl'
-    version = '1.0.2f'
+    version = '1.0.2g'
     licenses = [License.BSD_like]
     stype = SourceType.TARBALL
     url = 'ftp://ftp.openssl.org/source/{0}-{1}.tar.gz'.format(name, version)

**Comment by ck3mp3r** [comment]
#50 does the trick...

**Comment by stefanalund** [comment]
Fixed now, thanks!
