### ISSUE TITLE
Bootstraping in raspberry pi 3 with libffi

### ISSUE THREAD

**Issue by StarForestInThePark** [EricssonResearch/cerbero#61]
(read first -> Im not good at engilsh. so please execuse my english is baaaad.)
 
well.... same as title. I was building openwebrtc source code in raspberry pi 3 (Architecture : armv7l) .  
when bootstraping I got the same error over and over again.

[(9/15) libffi -> fetch ]
-----> Step done
[(9/15) libffi -> extract ]
Running command 'git reset --hard 60e4250a77eb3fde500bfd68ec40519fe34b21bd'
HEAD is now at 60e4250 make executable
Running command 'git branch cerbero_build'
fatal: A branch named 'cerbero_build' already exists.
Running command 'git checkout cerbero_build'
Already on 'cerbero_build'
Running command 'git reset --hard 60e4250a77eb3fde500bfd68ec40519fe34b21bd'
HEAD is now at 60e4250 make executable
Running command 'git clone /home/pi/project/cerbero/build/sources/local/libffi -s -b cerbero_buil
d .'
Cloning into '.'...
done.
Running command 'git config user.email'
Running command 'git config user.email "cerbero@gstreamer.freedesktop.org"'
Running command 'git config user.name'
Running command 'git config user.name "Cerbero Build System"'
Running command 'git submodule init'
Running command 'git submodule sync'
Running command 'git submodule update'
Running command 'git submodule sync'
Running command 'git am --ignore-whitespace /home/pi/project/cerbero/recipes/libffi/0001-libffi-D
on-t-be-smart-about-toolexeclibdir.patch'

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <pi@<myhostname>>) not allowed
You need to set your committer info first

***** Error running 'bootstrap' command:
Recipe 'libffi' failed at the build step 'extract'

Any idea how can I fix this error?

**Comment by superdump** [comment]
Change "you@example.com" to your email address and "Your Name" to your name in the commands below:

```
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
```

When you have run them, re-run the build process.

**Comment by StarForestInThePark** [comment]
thanks to reply!!!

I was changing source code /path/to/sources/cerbero/cerbero/utils/git.py
commands "git config user.email" -> "git config --global user.email"

and It work like a charm. 

BTW. should I close this issue?
